export const TEAM_INTRO =
  "Si la consultoría y la investigación de mercado tradicional tuvieran un hijo Millenial que se cree Centennial, nosotros seríamos el resultado.";

export const TEAM_MEMBERS = [
  {
    slug: "anais-freitas",
    name: "Anais Freitas",
    role: "Managing Partner | Strategy & Research",
    bio: "Anais combina diseño, research y estrategia con una lectura muy clara del negocio. Tiene más de 10 años creando y optimizando productos y experiencias digitales en Scotiabank, iVisa.com y proyectos en tecnología y servicios. En HABLA conecta comportamiento real, decisiones estratégicas y soluciones que sí se pueden ejecutar.",
    linkedin:
      "https://www.linkedin.com/in/anais-freitas-el%C3%A9spuru-54375073/",
    image: "/team/anaisfreitasHABLALATAM.png",
    accentClass: "bg-[#006AEF]",
  },
  {
    slug: "patricio-yrigoyen",
    name: "Patricio Yrigoyen",
    role: "Partner | Strategy & Data",
    bio: "Patricio trabaja en la intersección entre datos, operaciones y experiencia de usuario. Ha liderado equipos y resuelto problemas complejos en Rappi, Taxi Beat y Aceros Arequipa. En HABLA traduce métricas, fricciones y dinámicas operativas en decisiones claras y oportunidades de impacto real.",
    linkedin: "https://www.linkedin.com/in/patricio-yrigoyen/",
    image: "/team/patricioyrigoyenHABLALATAM.png",
    accentClass: "bg-[#006AEF]",
  },
  {
    slug: "santiago-burga",
    name: "Santiago Burga",
    role: "Partner | Strategy & Product",
    bio: "Santiago combina producto, tecnología y diseño con una fuerte orientación a ejecución. Ha trabajado en iVisa.com y Rappi liderando iniciativas de desarrollo y optimización de experiencias digitales. Ingeniero Industrial por la UTEC y MMM en Kellogg, hoy lidera la implementación de IA dentro de los procesos operativos de HABLA.",
    linkedin: "https://www.linkedin.com/in/santiagoburgabenavides/",
    image: "/team/santiagoburgaHABLALATAM.png",
    accentClass: "bg-[#006AEF]",
  },
  {
    slug: "carlos-galvez",
    name: "Carlos Gálvez",
    role: "Collaborator | Market Research",
    bio: "Carlos cuenta con más de 13 años de experiencia en investigación de mercados en agencias multinacionales como GfK, Ipsos y Kantar. Es psicólogo social y docente en temas de innovación y liderazgo. En HABLA aporta profundidad analítica, criterio estratégico y una lectura sólida del comportamiento del consumidor.",
    linkedin: null,
    image: "/team/carlosgalvezHABLALATAM.png",
    accentClass: "bg-[#eeff90]",
  },
  {
    slug: "pierina-ponce",
    name: "Pierina Ponce",
    role: "Collaborator | Product Manager",
    bio: "Pierina combina visión comercial y de producto, con más de 10 años de experiencia en retail, consumo masivo y fintech. Ha liderado productos y estrategias digitales en Niubiz, Kasnet, Ontop e Izipay. En HABLA aporta lectura estratégica, criterio de producto y foco en aterrizar ideas en soluciones reales.",
    linkedin: "https://www.linkedin.com/in/pierinaponce/",
    image: "/team/PierinaponceHABLALATAM.png",
    accentClass: "bg-[#eeff90]",
  },
  {
    slug: "sheila-acuna",
    name: "Sheila Acuña",
    role: "Collaborator | UX Research",
    bio: "Sheila es especialista en investigación de usuarios, con trayectoria en Scotiabank, Banco de Crédito BCP, Agile Wise, Eureka Research y Lava Innovation. Su fortaleza está en detectar patrones, tensiones y motivaciones profundas detrás del comportamiento. En HABLA ayuda a convertir hallazgos en decisiones que realmente mueven la aguja.",
    linkedin: "https://www.linkedin.com/in/sheila-acu%C3%B1a-obreg%C3%B3n/",
    image: "/team/sheilaacuñaHABLALATAM.png",
    accentClass: "bg-[#eeff90]",
  },
  {
    slug: "silvia-angulo",
    name: "Silvia Angulo",
    role: "Collaborator | UX Research",
    bio: "Silvia aporta una mirada estratégica construida desde años de trabajo en innovación, research y diseño de servicios. Ha colaborado con Scotiabank, Laureate, Pacífico, UTEC y Continuum HQ. En HABLA suma criterio, profundidad analítica y una fuerte orientación a decisiones accionables.",
    linkedin: "https://www.linkedin.com/in/silviaangulogamero/",
    image: "/team/silviaanguloHABLALATAM.png",
    accentClass: "bg-[#eeff90]",
  },
  {
    slug: "lady-vargas",
    name: "Lady Vargas",
    role: "Operations Lead",
    bio: "Lady es arquitecta egresada de la PUCP y fue la primera persona en sumarse a HABLA. Lidera las operaciones detrás de la magia, coordinando el reclutamiento a través de la comunidad, la base de datos histórica y el equipo en campo. Gracias a su trabajo, HABLA llega a las personas correctas en cada proyecto.",
    linkedin: "https://www.linkedin.com/in/lady-vargas-9ba74913a/",
    image: "/team/ladyvargasHABLALATAM.png",
    accentClass: "bg-[#E295E0]",
  },
  {
    slug: "maria-jose-tola",
    name: "María José Tola",
    role: "Brand & Growth Manager",
    bio: "Majo llegó como content creator y rápidamente evolucionó hacia un rol clave como brand manager. Lidera el seguimiento del pipeline comercial y gestiona cada punto de contacto entre HABLA y sus clientes: materiales, web, redes, WhatsApp y experiencias presenciales. Además, impulsa redes, eventos y comunidad.",
    linkedin:
      "https://www.linkedin.com/in/maria-jose-tola-dourojeanni-2674a5202/",
    image: "/team/mariajosetolaHABLALATAM.png",
    accentClass: "bg-[#E295E0]",
  },
  {
    slug: "milagros-freitas",
    name: "Milagros Freitas",
    role: "Advisor | Market Research",
    bio: "Milagros cuenta con más de 30 años de experiencia en investigación de mercados, tanto en agencias como en empresas. Ha liderado proyectos y equipos en Synovate, Ipsos, Datum y CCR. En HABLA aporta criterio estratégico, solidez metodológica y una mirada experta para la toma de decisiones.",
    linkedin: "https://www.linkedin.com/in/milagros-freitas-2930a451/",
    image: "/team/milagrosfreitasHABLALATAM.png",
    accentClass: "bg-[#E295E0]",
  },
  {
    slug: "nicolle-hazard",
    name: "Nicolle Hazard",
    role: "Advisor | Product Design",
    bio: "Nicolle diseña productos y servicios pensando en cómo las personas realmente los usan. Tiene experiencia en Skyward.AI, Fintoc, Prende, Dr. Wen y proyectos vinculados a UX y service design. En HABLA aporta estructura, criterio de diseño y foco en crear experiencias simples, claras y funcionales.",
    linkedin: "https://www.linkedin.com/in/nicollehazard/",
    image: "/team/nicollehazardHABLALATAM.png",
    accentClass: "bg-[#E295E0]",
  },
];
